// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Primary content in *color-grading → Slice zone → Añadir contenido → Primary*
 */
export interface ColorGradingDocumentDataBodyAnadirContenidoSlicePrimary {
  /**
   * product_title field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título del contenido
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_title: prismic.TitleField;

  /**
   * product thumbnail field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_thumbnail: prismic.ImageField<never>;

  /**
   * product type field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Tipo de contenido
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  product_type: prismic.SelectField<
    | "largometraje"
    | "cortometraje"
    | "serie"
    | "videoclip"
    | "comercial"
    | "reels-cursos"
    | "documentales"
  >;

  /**
   * product year field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Año de lanzamiento
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_year: prismic.RichTextField;

  /**
   * Dirgido por... field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Dirigido por...
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_directed_by
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_directed_by: prismic.RichTextField;

  /**
   * Dirección de fotografía por... field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Dirección de fotografía por...
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_photography_by
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_photography_by: prismic.RichTextField;

  /**
   * Dirección de arte por... field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Dirección de arte por...
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_art_by
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_art_by: prismic.RichTextField;

  /**
   * Producido por... field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Producido por...
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_produced_by
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_produced_by: prismic.RichTextField;

  /**
   * ID de Vimeo field in *color-grading → Slice zone → Añadir contenido → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ID de Vimeo
   * - **API ID Path**: color-grading.body[].anadir_contenido.primary.product_vimeo_id
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_vimeo_id: prismic.RichTextField;
}

/**
 * Slice for *color-grading → Slice zone*
 */
export type ColorGradingDocumentDataBodyAnadirContenidoSlice = prismic.Slice<
  "anadir_contenido",
  Simplify<ColorGradingDocumentDataBodyAnadirContenidoSlicePrimary>,
  never
>;

type ColorGradingDocumentDataBodySlice =
  ColorGradingDocumentDataBodyAnadirContenidoSlice;

/**
 * Content for color-grading documents
 */
interface ColorGradingDocumentData {
  /**
   * title field in *color-grading*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: color-grading.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice zone field in *color-grading*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: color-grading.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<ColorGradingDocumentDataBodySlice>;
}

/**
 * color-grading document from Prismic
 *
 * - **API ID**: `color-grading`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ColorGradingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ColorGradingDocumentData>,
    "color-grading",
    Lang
  >;

/**
 * Primary content in *educacional → Slice zone → Nueva institución → Primary*
 */
export interface EducacionalDocumentDataBodyNuevaInstitucionSlicePrimary {
  /**
   * Lugar field in *educacional → Slice zone → Nueva institución → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Nombre del lugar donde se llevó a cabo el curso
   * - **API ID Path**: educacional.body[].nueva_institucion.primary.place
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  place: prismic.TitleField;

  /**
   * Logo field in *educacional → Slice zone → Nueva institución → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: educacional.body[].nueva_institucion.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Item content in *educacional → Slice zone → Nueva institución → Items*
 */
export interface EducacionalDocumentDataBodyNuevaInstitucionSliceItem {
  /**
   * Imagen para carousel field in *educacional → Slice zone → Nueva institución → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: educacional.body[].nueva_institucion.items.carousel_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carousel_image: prismic.ImageField<never>;
}

/**
 * Slice for *educacional → Slice zone*
 */
export type EducacionalDocumentDataBodyNuevaInstitucionSlice = prismic.Slice<
  "nueva_institucion",
  Simplify<EducacionalDocumentDataBodyNuevaInstitucionSlicePrimary>,
  Simplify<EducacionalDocumentDataBodyNuevaInstitucionSliceItem>
>;

type EducacionalDocumentDataBodySlice =
  EducacionalDocumentDataBodyNuevaInstitucionSlice;

/**
 * Content for educacional documents
 */
interface EducacionalDocumentData {
  /**
   * título field in *educacional*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título de la sección
   * - **API ID Path**: educacional.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Información educacional field in *educacional*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detalles e información para sección "Educacional"
   * - **API ID Path**: educacional.educational_info
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  educational_info: prismic.RichTextField;

  /**
   * Encabezado lista instituciones field in *educacional*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título para la sección con logos de instituciones
   * - **API ID Path**: educacional.institutes_header_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  institutes_header_title: prismic.TitleField;

  /**
   * Slice zone field in *educacional*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: educacional.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<EducacionalDocumentDataBodySlice>;
}

/**
 * educacional document from Prismic
 *
 * - **API ID**: `educacional`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EducacionalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EducacionalDocumentData>,
    "educacional",
    Lang
  >;

/**
 * Content for index documents
 */
interface IndexDocumentData {
  /**
   * Imagen del hero field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.imagen_del_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen_del_hero: prismic.ImageField<never>;
}

/**
 * index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<IndexDocumentData>, "index", Lang>;

/**
 * Primary content in *nosotros → Slice zone → Miembro → Primary*
 */
export interface NosotrosDocumentDataBodyMiembroSlicePrimary {
  /**
   * Nombre field in *nosotros → Slice zone → Miembro → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Nombre del miembro
   * - **API ID Path**: nosotros.body[].miembro.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * portrait field in *nosotros → Slice zone → Miembro → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.body[].miembro.primary.portrait
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portrait: prismic.ImageField<never>;
}

/**
 * Item content in *nosotros → Slice zone → Miembro → Items*
 */
export interface NosotrosDocumentDataBodyMiembroSliceItem {
  /**
   * Información field in *nosotros → Slice zone → Miembro → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Información sobre el miembro
   * - **API ID Path**: nosotros.body[].miembro.items.member_data
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  member_data: prismic.RichTextField;
}

/**
 * Slice for *nosotros → Slice zone*
 */
export type NosotrosDocumentDataBodyMiembroSlice = prismic.Slice<
  "miembro",
  Simplify<NosotrosDocumentDataBodyMiembroSlicePrimary>,
  Simplify<NosotrosDocumentDataBodyMiembroSliceItem>
>;

type NosotrosDocumentDataBodySlice = NosotrosDocumentDataBodyMiembroSlice;

/**
 * Content for nosotros documents
 */
interface NosotrosDocumentData {
  /**
   * Título field in *nosotros*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título de la sección
   * - **API ID Path**: nosotros.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * sobre nosotros field in *nosotros*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Información sobre Crows Nest
   * - **API ID Path**: nosotros.about_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_us: prismic.RichTextField;

  /**
   * nosotros top image field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.nosotros_top_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  nosotros_top_image: prismic.ImageField<never>;

  /**
   * Slice zone field in *nosotros*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<NosotrosDocumentDataBodySlice>;
}

/**
 * nosotros document from Prismic
 *
 * - **API ID**: `nosotros`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NosotrosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NosotrosDocumentData>,
    "nosotros",
    Lang
  >;

/**
 * Primary content in *noticias → Slice zone → Noticia → Primary*
 */
export interface NoticiasDocumentDataBodyNoticiaSlicePrimary {
  /**
   * article header field in *noticias → Slice zone → Noticia → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título de la noticia
   * - **API ID Path**: noticias.body[].noticia.primary.article_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_header: prismic.TitleField;

  /**
   * article image field in *noticias → Slice zone → Noticia → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: noticias.body[].noticia.primary.article_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  article_image: prismic.ImageField<never>;

  /**
   * news_portal field in *noticias → Slice zone → Noticia → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Medio en el que fue publicada originalmente
   * - **API ID Path**: noticias.body[].noticia.primary.news_portal
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  news_portal: prismic.RichTextField;

  /**
   * article excerpt field in *noticias → Slice zone → Noticia → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detalle de la noticia
   * - **API ID Path**: noticias.body[].noticia.primary.article_excerpt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_excerpt: prismic.RichTextField;

  /**
   * article link field in *noticias → Slice zone → Noticia → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link a la noticia original
   * - **API ID Path**: noticias.body[].noticia.primary.article_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article_link: prismic.LinkField;
}

/**
 * Slice for *noticias → Slice zone*
 */
export type NoticiasDocumentDataBodyNoticiaSlice = prismic.Slice<
  "noticia",
  Simplify<NoticiasDocumentDataBodyNoticiaSlicePrimary>,
  never
>;

type NoticiasDocumentDataBodySlice = NoticiasDocumentDataBodyNoticiaSlice;

/**
 * Content for noticias documents
 */
interface NoticiasDocumentData {
  /**
   * title field in *noticias*
   *
   * - **Field Type**: Title
   * - **Placeholder**: noticias
   * - **API ID Path**: noticias.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice zone field in *noticias*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: noticias.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<NoticiasDocumentDataBodySlice>;
}

/**
 * noticias document from Prismic
 *
 * - **API ID**: `noticias`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NoticiasDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NoticiasDocumentData>,
    "noticias",
    Lang
  >;

/**
 * Primary content in *partners → Slice zone → Nuevo Partner → Primary*
 */
export interface PartnersDocumentDataBodyNuevaInstitucionSlicePrimary {
  /**
   * Lugar field in *partners → Slice zone → Nuevo Partner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Nombre del partner
   * - **API ID Path**: partners.body[].nueva_institucion.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Logo field in *partners → Slice zone → Nuevo Partner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.body[].nueva_institucion.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * url field in *partners → Slice zone → Nuevo Partner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link al partner
   * - **API ID Path**: partners.body[].nueva_institucion.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Slice for *partners → Slice zone*
 */
export type PartnersDocumentDataBodyNuevaInstitucionSlice = prismic.Slice<
  "nueva_institucion",
  Simplify<PartnersDocumentDataBodyNuevaInstitucionSlicePrimary>,
  never
>;

type PartnersDocumentDataBodySlice =
  PartnersDocumentDataBodyNuevaInstitucionSlice;

/**
 * Content for partners documents
 */
interface PartnersDocumentData {
  /**
   * título field in *partners*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título de la sección
   * - **API ID Path**: partners.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Información partners field in *partners*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detalles e información para sección "Partners"
   * - **API ID Path**: partners.partners_info
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  partners_info: prismic.RichTextField;

  /**
   * Encabezado lista instituciones field in *partners*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título para la sección con logos de partners
   * - **API ID Path**: partners.partners_header_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  partners_header_title: prismic.TitleField;

  /**
   * Slice zone field in *partners*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<PartnersDocumentDataBodySlice>;
}

/**
 * partners document from Prismic
 *
 * - **API ID**: `partners`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartnersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PartnersDocumentData>,
    "partners",
    Lang
  >;

/**
 * Content for servicios documents
 */
interface ServiciosDocumentData {
  /**
   * title field in *servicios*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * service-full-width-image field in *servicios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.service-full-width-image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "service-full-width-image": prismic.ImageField<never>;
}

/**
 * servicios document from Prismic
 *
 * - **API ID**: `servicios`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiciosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServiciosDocumentData>,
    "servicios",
    Lang
  >;

export type AllDocumentTypes =
  | ColorGradingDocument
  | EducacionalDocument
  | IndexDocument
  | NosotrosDocument
  | NoticiasDocument
  | PartnersDocument
  | ServiciosDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ColorGradingDocument,
      ColorGradingDocumentData,
      ColorGradingDocumentDataBodyAnadirContenidoSlicePrimary,
      ColorGradingDocumentDataBodySlice,
      EducacionalDocument,
      EducacionalDocumentData,
      EducacionalDocumentDataBodyNuevaInstitucionSlicePrimary,
      EducacionalDocumentDataBodyNuevaInstitucionSliceItem,
      EducacionalDocumentDataBodySlice,
      IndexDocument,
      IndexDocumentData,
      NosotrosDocument,
      NosotrosDocumentData,
      NosotrosDocumentDataBodyMiembroSlicePrimary,
      NosotrosDocumentDataBodyMiembroSliceItem,
      NosotrosDocumentDataBodySlice,
      NoticiasDocument,
      NoticiasDocumentData,
      NoticiasDocumentDataBodyNoticiaSlicePrimary,
      NoticiasDocumentDataBodySlice,
      PartnersDocument,
      PartnersDocumentData,
      PartnersDocumentDataBodyNuevaInstitucionSlicePrimary,
      PartnersDocumentDataBodySlice,
      ServiciosDocument,
      ServiciosDocumentData,
      AllDocumentTypes,
    };
  }
}
